apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hltg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-hltg@sha256:f38b96935f046139a8202a3a57a35d5d5576c296eec3b8e4d95f01b1fd81457e
        name: my-nodejs
        resources: {}
status: {}
